config/routes.rb
Rails.application.routes.draw do
  resources :users do
  	resources :addresses
  end
  root 'users#new'
end

app/models/address.rb
# == Schema Information
#
# Table name: addresses
#
#  id         :integer          not null, primary key
#  city       :string
#  state      :string
#  country    :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  pincode    :string
#

class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  email      :string
#  mobile     :string
#  password   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  dob        :datetime
#  gender     :string
#

class User < ApplicationRecord
	has_many :addresses, dependent: :destroy
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true
	validates :mobile, presence: true
	validates :password, presence: true
	validates :gender, presence:true
	validates :dob, presence:true


	def validate_date_of_birth
	#	lowest_date = '1920-01-01'
	#	highest_date = Time.now

		 dob < Date.today && dob > Date.today.year - 120 
    #input_date.between?(lowest_date, highest_date)
	end

  def check_if_name_contains_numbers

  	 /[0-9]/.match(first_name).nil?
  	 
  end
	# def check_if_name_contains_numbers
 #   x = 0
 #   flag = false
 #   name = first_name
 #   loop do
 # 	    y = x
 # 	   if name.include? y.to_s
 # 	   	  flag = true
 # 		    break
 # 	   end
 # 	   if x == 9
 # 		    break
 # 	   end
 # 	   x += 1
 #    end
 #   return flag
 #  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
	def index
	end

	def new
		@user = User.find(params[:user_id])
	end

	def show
		@address = Address.find_by(user_id: params[:user_id])
	end

	def create
		@user = User.find(params[:user_id])
    @address = @user.addresses.create(address_params)
    redirect_to user_address_path(id: params[:user_id])
	end


	private
	def address_params
		params.require(:address).permit(:city, :state, :country, :pincode)
	end

	# def destroy
	# 	@user = User.find(params[:user_id])
	# 	@address = @user.addresses.find(params[:id])
	# 	@address.destroy
	# 	redirect_to users_path
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
		respond_to do |format|
			format.html
			format.json {render :json => @users}
		end
	end
	def new
		@user = User.new
	end
  
  def show
  	@user = User.find(params[:id])
  	#render plain: params[:user].inspect
  end

	def create
		@user = User.new(user_params)
		if @user.save
		redirect_to @user
	else 
		render 'new'
	end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :dob, :gender, :email, :mobile, :password)
	end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/new.html.erb
<center><h1>Add Your Address</h1><br><br>
<%= form_with scope: :address, url: user_addresses_path(@user), local: true do |form| %>
<table>
<tr>
  <td><%= form.label :'City' %></td>
  <td><%= form.text_field :city %></td>
  </tr>
  <tr>
  <td><%= form.label :'State' %></td>
  <td><%= form.text_field :state %></td>
  </tr>
  <tr>
  <td><%= form.label :'Country' %></td>
  <td><%= form.text_field :country %></td>
  </tr>
  <tr>
  <td><%= form.label :'Pin Code' %></td>
  <td><%= form.text_field :pincode %></td>
  </tr>
  </table>  
  <%=form.submit %>
  <% end %>
  </center>

app/views/addresses/show.html.erb
<center><h1>Your Address Details</h1><br><br>
<table border="2">
 <tr>
  <td><strong>City:</strong></td>
  <td><%= @address.city %></td>
  </tr>
  <tr>
  <td><strong>State:</strong></td>
  <td><%= @address.state %></td>
  </tr>
  <tr>
  <td><strong>Country:</strong></td>
  <td><%= @address.country %></td>
  </tr>
  <tr>
  <td><strong>Pin Code:</strong></td>
  <td><%= @address.pincode %></td>
  </tr>

</table>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<center><h1>Details Of All The Users Registered Till Now...</h1>
<table border="2">
  <tr>
	<th>First Name</th>
	<th>Last Name</th>
	<th>Email</th>
	<th>Mobile</th>
	<th colspan="3"></th>
	</tr>

	<% @users.each do |user| %>
	<tr>
	 <td><%= user.first_name %></td>
	 <td><%= user.last_name %></td>
	 <td><%= user.email %></td>
	 <td><%= user.mobile %></td>
	 <td><%= link_to 'View Profile', user_path(user) %></td>
	 <td><%= link_to 'Delete', user,
	 												method: :delete,
	 												data: {confirm: 'Are You Sure..??'} %></td>
	 </tr>
	 <% end %>
	 </table><br>
	 <%= link_to 'Create New User', new_user_path %>
	 &nbsp; &nbsp;
	 <%= link_to 'Show All Users', users_path %>
	 </center>

app/views/users/new.html.erb
<center><h1>New User Registration</h1>

<%= form_with scope: :user, url: users_path, local: true do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<table>
	<tr>
	<td><%= form.label :'First Name' %></td>
	<td><%= form.text_field :first_name %></td>
	</tr>

	<tr>
	<td><%= form.label :'Last Name' %></td>
	<td><%= form.text_field :last_name %></td>
	</tr>
	<tr>
	<td><%= form.label :'Date Of Birth' %></td>
	<td><%= form.date_field :dob %></td>
	</tr>
	<tr>
	<td><%= form.label :'Gender' %></td>
	<td><%= form.text_field :gender %></td>
	</tr>

	<tr>
	<td><%= form.label :Email %></td>
	<td><%= form.text_field :email %></td>
	</tr>
	<tr>
	<td><%= form.label :Mobile %></td>
	<td><%= form.text_field :mobile %></td>
	</tr>
	<tr>
	<td><%= form.label :Password %></td>
	<td><%= form.password_field :password %></td>
	</tr>
	</table>
	<%= form.submit %>
	<%= link_to 'Show All Users', users_path %>
	 <% end %>
	 </center>

app/views/users/show.html.erb
<center>
<table border="2">
 <tr>
   <td><strong>First Name: </strong></td>
   <td><%= @user.first_name %></td><br>
 </tr>
 <tr>
   <td><strong>Last Name:</strong></td>
   <td> <%= @user.last_name %></td><br>
  </tr>
  <tr> 
    <td><strong>Email:</strong></td>
    <td><%= @user.email %></td><br>
  </tr>
  <tr>
     <td><strong>Mobile:</strong></td>
     <td><%= @user.mobile %></td><br>
     </tr>
   <tr>
     <td><strong>Gender:</strong></td>
     <td><%= @user.gender %></td><br>
   </tr>
   <tr>
     <td><strong>Date Of Birth:</strong></td>
     <td><%= @user.dob%></td><br>
   </tr>    
     </table><br>
     <%= link_to 'Add Address', new_user_address_path(@user) %>
     &nbsp; &nbsp;
     <%= link_to 'Show All Users', users_path %>
     </center>